# .github/workflows/deploy.yml
name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master      # или ваша основная ветка
  workflow_dispatch: {}

permissions:
  contents: write  # даём GITHUB_TOKEN право пушить в репо

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build production bundle
        run: npm run build:gh

      - name: List build output
        run: ls -R dist/ymaps-distance

      - name: Determine publish directory
        run: |
          if [ -f dist/ymaps-distance/index.html ]; then
            echo "PUBLISH_DIR=dist/ymaps-distance" >> $GITHUB_ENV
          elif [ -f dist/ymaps-distance/browser/index.html ]; then
            echo "PUBLISH_DIR=dist/ymaps-distance/browser" >> $GITHUB_ENV
          else
            echo "❌ index.html not found!" >&2
            exit 1
          fi

      - name: Prepare SPA 404 fallback
        run: |
          cd "${PUBLISH_DIR}"
          # делаем 404.html точной копией index.html
          cp index.html 404.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.PUBLISH_DIR }}
          publish_branch: gh-pages
          enable_jekyll: false
          keep_files: false
          force_orphan: true
